/**    Copyright 2022, Reinhard Herzog (Fraunhofer IOSB)

Licensed under the Apache License, Version 2.0 (the "License")
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http: //www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package org.nato.ivct.rpr.interactions;

import org.nato.ivct.rpr.HLAroot;
import org.nato.ivct.rpr.RprBuilderException;
import org.nato.ivct.rpr.datatypes.EventIdentifierStruct;

import hla.rti1516e.exceptions.FederateNotExecutionMember;
import hla.rti1516e.exceptions.NameNotFound;
import hla.rti1516e.exceptions.NotConnected;
import hla.rti1516e.exceptions.RTIinternalError;


/***
 * Communicates information associated with the firing or launch of a munition.
 */
public class WeaponFire extends HLAinteractionRoot {

    public enum Attributes {
        EventIdentifier,
        FireControlSolutionRange,
        FireMissionIndex,
        FiringLocation,
        FiringObjectIdentifier,
        FuseType,
        InitialVelocityVector,
        MunitionObjectIdentifier,
        MunitionType,
        QuantityFired,
        RateOfFire,
        TargetObjectIdentifier,
        WarheadType
    }


    public WeaponFire()
            throws NameNotFound, FederateNotExecutionMember, NotConnected, RTIinternalError, RprBuilderException {
        super();
        addParameter(Attributes.EventIdentifier.name(), new EventIdentifierStruct());
        addParameter(Attributes.FireControlSolutionRange.name(), HLAroot.getEncoderFactory().createHLAfloat32BE());
        //TODO Auto-generated constructor stub
        // addParameter(Attributes.FireMissionIndex.name(), null);
        // addParameter(Attributes.FiringLocation.name(), null);
        // addParameter(Attributes.FiringObjectIdentifier.name(), null);
        // addParameter(Attributes.FuseType.name(), null);
        // addParameter(Attributes.InitialVelocityVector.name(), null);
        // addParameter(Attributes.MunitionObjectIdentifier.name(), null);
        // addParameter(Attributes.MunitionType.name(), null);
        // addParameter(Attributes.QuantityFired.name(), null);
        // addParameter(Attributes.RateOfFire.name(), null);
        // addParameter(Attributes.TargetObjectIdentifier.name(), null);
        // addParameter(Attributes.WarheadType.name(), null);

    }
    
    /**
     * An ID, generated by the issuing federate, used to associate related fire and detonation events.
     */
    public EventIdentifierStruct getEventIdentifier() {
        return (EventIdentifierStruct) getParameter(Attributes.EventIdentifier.name());
    }
    public void setEventIdentifier(EventIdentifierStruct value) {
        addParameter(Attributes.EventIdentifier.name(), value);
    }

    // TODO add remaining getter and setter
}




/**
 * 
            <interactionClass>
                <name>WeaponFire</name>
                <sharing>PublishSubscribe</sharing>
                <transportation>HLAbestEffort</transportation>
                <order>Receive</order>
                <semantics>Communicates information associated with the firing or launch of a munition.</semantics>
                <parameter>
                    <name>EventIdentifier</name>
                    <dataType>EventIdentifierStruct</dataType>
                    <semantics>An ID, generated by the issuing federate, used to associate related fire and detonation events.</semantics>
                </parameter>
                <parameter>
                    <name>FireControlSolutionRange</name>
                    <dataType>LengthMeterFloat32</dataType>
                    <semantics>The range used in the fire control solution. Zero if the range is unknown or inapplicable.</semantics>
                </parameter>
                <parameter>
                    <name>FireMissionIndex</name>
                    <dataType>UnsignedInteger32</dataType>
                    <semantics>A unique index to identify the fire mission (used to associate weapon fire interactions in a single fire mission).</semantics>
                </parameter>
                <parameter>
                    <name>FiringLocation</name>
                    <dataType>WorldLocationStruct</dataType>
                    <semantics>The location, in world coordinates, from which the munition was launched.</semantics>
                </parameter>
                <parameter notes="RPRnoteWarfare2">
                    <name>FiringObjectIdentifier</name>
                    <dataType>RTIobjectId</dataType>
                    <semantics>The object instance ID of the entity firing the munition.</semantics>
                </parameter>
                <parameter>
                    <name>FuseType</name>
                    <dataType>FuseTypeEnum16</dataType>
                    <semantics>The type of fuse on the munition.</semantics>
                </parameter>
                <parameter>
                    <name>InitialVelocityVector</name>
                    <dataType>VelocityVectorStruct</dataType>
                    <semantics>The velocity vector of the munition when fired.</semantics>
                </parameter>
                <parameter notes="RPRnoteWarfare1">
                    <name>MunitionObjectIdentifier</name>
                    <dataType>RTIobjectId</dataType>
                    <semantics>The object instance ID of the fired munition, if an object instance is registered.</semantics>
                </parameter>
                <parameter>
                    <name>MunitionType</name>
                    <dataType>EntityTypeStruct</dataType>
                    <semantics>The type of munition being fired.</semantics>
                </parameter>
                <parameter>
                    <name>QuantityFired</name>
                    <dataType>UnsignedInteger16</dataType>
                    <semantics>The number of rounds fired in the burst.</semantics>
                </parameter>
                <parameter>
                    <name>RateOfFire</name>
                    <dataType>UnsignedInteger16</dataType>
                    <semantics>The rate of fire in rounds per minute when quantity &gt; 1. Zero otherwise.</semantics>
                </parameter>
                <parameter notes="RPRnoteWarfare1">
                    <name>TargetObjectIdentifier</name>
                    <dataType>RTIobjectId</dataType>
                    <semantics>The object instance ID of the intended target (if any).</semantics>
                </parameter>
                <parameter>
                    <name>WarheadType</name>
                    <dataType>WarheadTypeEnum16</dataType>
                    <semantics>The type of warhead fitted to the munition being fired.</semantics>
                </parameter>
            </interactionClass>
 */